FROM golang:alpine AS build-stage

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /main ./main.go

FROM gcr.io/distroless/static-debian12 AS build-release

WORKDIR /

COPY --from=build-stage /main /main

ENTRYPOINT ["/main"]
